// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UniStay.Infrastructure.Database;

#nullable disable

namespace UniStay.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260905090000_AddPasswordRecoveryContexts")]
    partial class AddPasswordRecoveryContexts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
        }
    }
}
